# Generated by Django 6.0.6 on 2026-07-09 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDriveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('drive_folder_id', models.CharField(max_length=128, unique=True)),
                ('folder_link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['student_id'], name='filehandler_student_d5666f_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriveFileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=128, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_link', models.URLField()),
                ('download_link', models.URLField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='filehandler.studentdrivefolder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('folder', 'file_name'), name='unique_file_per_folder')],
            },
        ),
    ]
