# Generated by Django 6.0.6 on 2026-07-09 06:36

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ICPCAmbassadorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number.')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('official_email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=255)),
                ('is_state_verified', models.BooleanField(default=False)),
                ('degree_program', models.CharField(max_length=100)),
                ('year_of_study', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year / Final')], max_length=1)),
                ('is_women_only_institution', models.BooleanField(default=False)),
                ('student_strength', models.PositiveIntegerField(blank=True, null=True)),
                ('awareness_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('active_participants_estimate', models.CharField(blank=True, max_length=100)),
                ('institution_has', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('non_participation_reasons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list)),
                ('biggest_challenge', models.TextField(blank=True)),
                ('awareness_plan', models.TextField(blank=True)),
                ('estimated_teams', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memberships', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list)),
                ('has_organized_event', models.BooleanField(default=False)),
                ('event_description', models.TextField(blank=True)),
                ('network_reach_estimate', models.PositiveIntegerField(blank=True, null=True)),
                ('aware_of_mentors', models.BooleanField(default=False)),
                ('mentor_details', models.TextField(blank=True)),
                ('faculty_encourages', models.BooleanField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('agrees_to_promote', models.BooleanField(default=False)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('is_included', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('approve', 'Approve'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='on_hold', max_length=10)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
