# Generated by Django 6.0.6 on 2026-07-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icpcambassadorapplication',
            name='is_included',
            field=models.BooleanField(default=False),
        ),
    ]
