# Generated by Django 6.0.6 on 2026-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_populate_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='icpcambassadorapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
