# Generated by Django 6.0.6 on 2026-07-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_remove_icpcambassadorapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpcambassadorapplication',
            name='approval_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('on_hold', 'On Hold'), ('rejected', 'Rejected'), ('nill', 'Nill')], default='nill', max_length=10),
        ),
    ]
