# Generated by Django 6.0.6 on 2026-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_alter_icpcambassadorapplication_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icpcambassadorapplication',
            name='approval_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('on_hold', 'On Hold'), ('rejected', 'Rejected')], default='on_hold', max_length=10),
        ),
    ]
